#!powershell

# Copyright: (c) 2026, Generated by Jarvis Ansible Collection Swarm
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#AnsibleRequires -CSharpUtil Ansible.Basic

$spec = @{
    options = @{
        vm_name = @{ type = "str"; required = $true }
        vmm_server = @{ type = "str"; required = $false }
        bus = @{ type = "int"; required = $false; default = 1 }
        lun = @{ type = "int"; required = $false; default = 0 }
        iso_path = @{ type = "str"; required = $false }
        state = @{ type = "str"; default = "present"; choices = @("present", "absent") }
    }
    supports_check_mode = $true
}

$module = [Ansible.Basic.AnsibleModule]::Create($args, $spec)

$vm_name = $module.Params.vm_name
$vmm_server = $module.Params.vmm_server
$bus = $module.Params.bus
$lun = $module.Params.lun
$iso_path = $module.Params.iso_path
$state = $module.Params.state

# Initialize result
$module.Result.changed = $false
$module.Result.dvd_drive = @{}

# Import VirtualMachineManager module
try {
    Import-Module VirtualMachineManager -ErrorAction Stop
} catch {
    $module.FailJson("Failed to import VirtualMachineManager module. Ensure SCVMM PowerShell module is installed.", $_)
}

# Connect to SCVMM server
try {
    if ($vmm_server) {
        $vmmConnection = Get-SCVMMServer -ComputerName $vmm_server -ErrorAction Stop
    } else {
        $vmmConnection = Get-SCVMMServer -ErrorAction Stop
    }
} catch {
    $module.FailJson("Failed to connect to SCVMM server '$vmm_server'.", $_)
}

# Helper function to build DVD drive properties for diff mode
Function Get-DvdDrivePropertiesDict {
    param($DvdDrive)

    $isoName = $null
    if ($DvdDrive.ISO) {
        $isoName = $DvdDrive.ISO.Name
    }

    return @{
        bus = $DvdDrive.Bus
        lun = $DvdDrive.LUN
        iso_path = $isoName
        vm_name = $DvdDrive.VMName
        name = $DvdDrive.Name
    }
}

# PATTERN: Get the VM first
try {
    $vm = Get-SCVirtualMachine -VMMServer $vmmConnection -Name $vm_name -ErrorAction SilentlyContinue
    if ($null -eq $vm) {
        $module.FailJson("VM '$vm_name' not found on SCVMM server.")
    }
} catch {
    $module.FailJson("Failed to query VM '$vm_name'.", $_)
}

# PATTERN: Check current state (GET)
try {
    $currentDvdDrive = Get-SCVirtualDVDDrive -VM $vm -ErrorAction SilentlyContinue | Where-Object { $_.Bus -eq $bus -and $_.LUN -eq $lun }
} catch {
    $module.FailJson("Failed to query DVD drive on bus $bus, LUN $lun for VM '$vm_name'.", $_)
}

# PATTERN: Decide action based on desired state
if ($state -eq "present") {
    if ($null -eq $currentDvdDrive) {
        # DVD drive doesn't exist, create it
        $module.Diff.before = @{}

        if (-not $module.CheckMode) {
            try {
                # Build creation parameters
                $createParams = @{
                    VM = $vm
                    Bus = $bus
                    LUN = $lun
                }

                # If ISO path is provided, attach it
                if ($iso_path) {
                    # Get the ISO from the library
                    $iso = Get-SCISO -VMMServer $vmmConnection | Where-Object { $_.Name -eq $iso_path -or $_.SharePath -eq $iso_path } | Select-Object -First 1
                    if ($null -eq $iso) {
                        $module.FailJson("ISO '$iso_path' not found in SCVMM library.")
                    }
                    $createParams.ISO = $iso
                }

                # PATTERN: Apply change (CREATE)
                $currentDvdDrive = New-SCVirtualDVDDrive @createParams -ErrorAction Stop

            } catch {
                $module.FailJson("Failed to create DVD drive on bus $bus, LUN $lun for VM '$vm_name'.", $_)
            }
        }

        $module.Result.changed = $true
        $module.Result.msg = "DVD drive on bus $bus, LUN $lun created successfully"

        if (-not $module.CheckMode) {
            $module.Result.dvd_drive = Get-DvdDrivePropertiesDict -DvdDrive $currentDvdDrive
            $module.Diff.after = $module.Result.dvd_drive
        } else {
            $module.Diff.after = @{
                bus = $bus
                lun = $lun
                iso_path = $iso_path
                vm_name = $vm_name
            }
        }

    } else {
        # DVD drive exists, check if update needed (ISO attachment change)
        $module.Diff.before = Get-DvdDrivePropertiesDict -DvdDrive $currentDvdDrive

        $currentIso = $currentDvdDrive.ISO
        $needsUpdate = $false
        $iso = $null

        # PATTERN: Compare current vs desired
        if ($iso_path) {
            # User wants an ISO attached
            $iso = Get-SCISO -VMMServer $vmmConnection | Where-Object { $_.Name -eq $iso_path -or $_.SharePath -eq $iso_path } | Select-Object -First 1
            if ($null -eq $iso) {
                $module.FailJson("ISO '$iso_path' not found in SCVMM library.")
            }

            # Check if current ISO is different or no ISO is attached
            if ($null -eq $currentIso -or $currentIso.ID -ne $iso.ID) {
                $needsUpdate = $true
            }
        } else {
            # User wants no ISO attached (eject)
            if ($null -ne $currentIso) {
                $needsUpdate = $true
            }
        }

        if ($needsUpdate) {
            if (-not $module.CheckMode) {
                try {
                    # Build update parameters
                    $updateParams = @{
                        VirtualDVDDrive = $currentDvdDrive
                    }

                    if ($iso_path) {
                        # Attach ISO
                        $updateParams.ISO = $iso
                    } else {
                        # Eject ISO
                        $updateParams.NoMedia = $true
                    }

                    # PATTERN: Apply change (UPDATE)
                    $currentDvdDrive = Set-SCVirtualDVDDrive @updateParams -ErrorAction Stop

                } catch {
                    $module.FailJson("Failed to update DVD drive on bus $bus, LUN $lun for VM '$vm_name'.", $_)
                }
            }

            $module.Result.changed = $true
            if ($iso_path) {
                $module.Result.msg = "DVD drive on bus $bus, LUN $lun updated with ISO '$iso_path'"
            } else {
                $module.Result.msg = "DVD drive on bus $bus, LUN $lun updated (ISO ejected)"
            }

        } else {
            $module.Result.changed = $false
            $module.Result.msg = "DVD drive on bus $bus, LUN $lun already in desired state"
        }

        if (-not $module.CheckMode) {
            $module.Result.dvd_drive = Get-DvdDrivePropertiesDict -DvdDrive $currentDvdDrive
            $module.Diff.after = $module.Result.dvd_drive
        } else {
            $module.Diff.after = $module.Diff.before
            if ($needsUpdate) {
                $module.Diff.after.iso_path = $iso_path
            }
        }
    }

} else {
    # state == "absent"
    if ($null -ne $currentDvdDrive) {
        # DVD drive exists, remove it
        $module.Diff.before = Get-DvdDrivePropertiesDict -DvdDrive $currentDvdDrive
        $module.Diff.after = @{}

        if (-not $module.CheckMode) {
            try {
                # PATTERN: Apply change (DELETE)
                Remove-SCVirtualDVDDrive -VirtualDVDDrive $currentDvdDrive -ErrorAction Stop
            } catch {
                $module.FailJson("Failed to remove DVD drive on bus $bus, LUN $lun for VM '$vm_name'.", $_)
            }
        }

        $module.Result.changed = $true
        $module.Result.msg = "DVD drive on bus $bus, LUN $lun removed successfully"

    } else {
        $module.Result.changed = $false
        $module.Result.msg = "DVD drive on bus $bus, LUN $lun already absent"
        $module.Diff.before = @{}
        $module.Diff.after = @{}
    }
}

$module.ExitJson()
