#!powershell

# Copyright: (c) 2026, Generated by Jarvis Universal Ansible Collection Swarm
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#AnsibleRequires -CSharpUtil Ansible.Basic

$spec = @{
    options = @{
        vm_name = @{
            type = "str"
            required = $true
        }
        vmm_server = @{
            type = "str"
            required = $true
        }
        checkpoint_name = @{
            type = "str"
            required = $true
        }
        description = @{
            type = "str"
            required = $false
        }
        state = @{
            type = "str"
            required = $true
            choices = @("present", "absent", "restored")
        }
    }
    supports_check_mode = $true
}

$module = [Ansible.Basic.AnsibleModule]::Create($args, $spec)

$vm_name = $module.Params.vm_name
$vmm_server = $module.Params.vmm_server
$checkpoint_name = $module.Params.checkpoint_name
$description = $module.Params.description
$state = $module.Params.state

$module.Result.changed = $false
$module.Result.vm_name = $vm_name
$module.Result.checkpoint_name = $checkpoint_name
$module.Result.checkpoint = @{}

# Import VirtualMachineManager module
try {
    Import-Module VirtualMachineManager -ErrorAction Stop
} catch {
    $module.FailJson("Failed to import VirtualMachineManager module. Ensure SCVMM PowerShell module is installed.", $_)
}

# Connect to SCVMM server
try {
    $vmmConnection = Get-SCVMMServer -ComputerName $vmm_server -ErrorAction Stop
} catch {
    $module.FailJson("Failed to connect to SCVMM server '$vmm_server'.", $_)
}

# Get the VM
try {
    $vm = Get-SCVirtualMachine -VMMServer $vmmConnection -Name $vm_name -ErrorAction Stop
} catch {
    $module.FailJson("Failed to find VM '$vm_name'.", $_)
}

# Helper function to get checkpoint properties
Function Get-CheckpointPropertiesDict {
    param($Checkpoint)

    if ($null -eq $Checkpoint) {
        return @{}
    }

    return @{
        name = $Checkpoint.Name
        description = $Checkpoint.Description
        vm_name = $Checkpoint.VMName
        checkpoint_id = $Checkpoint.CheckpointID.ToString()
        added_time = $Checkpoint.AddedTime.ToString("yyyy-MM-ddTHH:mm:ss")
        is_most_recent = $Checkpoint.IsMostRecentCheckpoint
    }
}

# PATTERN: Check current state (GET)
try {
    $currentCheckpoint = Get-SCVMCheckpoint -VM $vm -Name $checkpoint_name -ErrorAction SilentlyContinue
} catch {
    $module.FailJson("Failed to query checkpoint '$checkpoint_name' for VM '$vm_name'.", $_)
}

# PATTERN: Decide action based on desired state
if ($state -eq "present") {
    if ($null -eq $currentCheckpoint) {
        # Checkpoint doesn't exist, create it
        $module.Diff.before = @{}

        if (-not $module.CheckMode) {
            try {
                # Build creation parameters
                $createParams = @{
                    VM = $vm
                    Name = $checkpoint_name
                }

                if ($description) {
                    $createParams.Description = $description
                }

                # PATTERN: Apply change (CREATE)
                $currentCheckpoint = New-SCVMCheckpoint @createParams -ErrorAction Stop

            } catch {
                $module.FailJson("Failed to create checkpoint '$checkpoint_name' for VM '$vm_name'.", $_)
            }
        }

        $module.Result.changed = $true
        $module.Result.msg = "Checkpoint '$checkpoint_name' created successfully"

        if (-not $module.CheckMode) {
            $module.Result.checkpoint = Get-CheckpointPropertiesDict -Checkpoint $currentCheckpoint
            $module.Diff.after = $module.Result.checkpoint
        } else {
            $module.Diff.after = @{
                name = $checkpoint_name
                vm_name = $vm_name
                description = $description
            }
        }

    } else {
        # Checkpoint exists, check if update needed
        $module.Diff.before = Get-CheckpointPropertiesDict -Checkpoint $currentCheckpoint

        # Compare description if provided
        $needsUpdate = $false
        if ($null -ne $description -and $currentCheckpoint.Description -ne $description) {
            $needsUpdate = $true
        }

        if ($needsUpdate) {
            if (-not $module.CheckMode) {
                try {
                    # PATTERN: Apply change (UPDATE)
                    # Note: SCVMM doesn't support updating checkpoint properties after creation
                    # This is documented behavior
                    $module.Warn("SCVMM does not support modifying checkpoint properties after creation. Checkpoint exists but description cannot be updated.")

                } catch {
                    $module.FailJson("Failed to update checkpoint '$checkpoint_name'.", $_)
                }
            }

            $module.Result.changed = $false
            $module.Result.msg = "Checkpoint '$checkpoint_name' exists but cannot be updated (SCVMM limitation)"

        } else {
            $module.Result.changed = $false
            $module.Result.msg = "Checkpoint '$checkpoint_name' already exists"
        }

        if (-not $module.CheckMode) {
            $module.Result.checkpoint = Get-CheckpointPropertiesDict -Checkpoint $currentCheckpoint
            $module.Diff.after = $module.Result.checkpoint
        } else {
            $module.Diff.after = $module.Diff.before
        }
    }

} elseif ($state -eq "absent") {
    # state == "absent"
    if ($null -ne $currentCheckpoint) {
        # Checkpoint exists, remove it
        $module.Diff.before = Get-CheckpointPropertiesDict -Checkpoint $currentCheckpoint
        $module.Diff.after = @{}

        if (-not $module.CheckMode) {
            try {
                # PATTERN: Apply change (DELETE)
                Remove-SCVMCheckpoint -VMCheckpoint $currentCheckpoint -ErrorAction Stop

            } catch {
                $module.FailJson("Failed to remove checkpoint '$checkpoint_name' for VM '$vm_name'.", $_)
            }
        }

        $module.Result.changed = $true
        $module.Result.msg = "Checkpoint '$checkpoint_name' removed successfully"

    } else {
        $module.Result.changed = $false
        $module.Result.msg = "Checkpoint '$checkpoint_name' already absent"
        $module.Diff.before = @{}
        $module.Diff.after = @{}
    }

} elseif ($state -eq "restored") {
    # state == "restored"
    if ($null -eq $currentCheckpoint) {
        $module.FailJson("Cannot restore checkpoint '$checkpoint_name' - checkpoint does not exist.")
    }

    # Checkpoint exists, restore it
    $module.Diff.before = @{
        current_vm_state = $vm.Status
        checkpoint_to_restore = $checkpoint_name
    }

    if (-not $module.CheckMode) {
        try {
            # PATTERN: Apply change (RESTORE)
            Restore-SCVMCheckpoint -VMCheckpoint $currentCheckpoint -ErrorAction Stop

            # Refresh VM object to get updated state
            $vm = Get-SCVirtualMachine -VMMServer $vmmConnection -Name $vm_name -ErrorAction Stop

        } catch {
            $module.FailJson("Failed to restore checkpoint '$checkpoint_name' for VM '$vm_name'.", $_)
        }
    }

    $module.Result.changed = $true
    $module.Result.msg = "Checkpoint '$checkpoint_name' restored successfully"

    if (-not $module.CheckMode) {
        $module.Result.checkpoint = Get-CheckpointPropertiesDict -Checkpoint $currentCheckpoint
        $module.Diff.after = @{
            restored_from_checkpoint = $checkpoint_name
            vm_state_after_restore = $vm.Status
        }
    } else {
        $module.Diff.after = @{
            restored_from_checkpoint = $checkpoint_name
        }
    }
}

$module.ExitJson()
