#!powershell
# -*- coding: utf-8 -*-

# Copyright: (c) 2026, Generated by Jarvis Universal Ansible Collection Swarm
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#AnsibleRequires -CSharpUtil Ansible.Basic

$spec = @{
    options = @{
        vmm_server = @{
            type = "str"
            required = $false
        }
        name = @{
            type = "str"
            required = $false
        }
        id = @{
            type = "str"
            required = $false
        }
        cloud = @{
            type = "str"
            required = $false
        }
        host_group = @{
            type = "str"
            required = $false
        }
        vm_host = @{
            type = "str"
            required = $false
        }
        status = @{
            type = "str"
            required = $false
            choices = @("Running", "Stopped", "Paused", "Saved", "PowerOff", "HostNotResponding", "UnderCreation", "UnderUpdate", "Missing")
        }
    }
    supports_check_mode = $true
}

$module = [Ansible.Basic.AnsibleModule]::Create($args, $spec)

$vmm_server = $module.Params.vmm_server
$name = $module.Params.name
$id = $module.Params.id
$cloud = $module.Params.cloud
$host_group = $module.Params.host_group
$vm_host = $module.Params.vm_host
$status = $module.Params.status

$module.Result.vms = @()

Function Connect-VMMServer {
    param(
        [string]$ServerName
    )

    try {
        # Import required module
        Import-Module VirtualMachineManager -ErrorAction Stop

        if ($ServerName) {
            $vmmConnection = Get-SCVMMServer -ComputerName $ServerName -ErrorAction Stop
        } else {
            # Try localhost connection
            $vmmConnection = Get-SCVMMServer -ComputerName "localhost" -ErrorAction Stop
        }

        return $vmmConnection
    } catch {
        $module.FailJson("Failed to connect to SCVMM server: $($_.Exception.Message)")
    }
}

Function Get-VMInfo {
    param(
        [object]$VM
    )

    $vmInfo = @{
        name = $VM.Name
        id = $VM.ID.ToString()
        status = $VM.Status.ToString()
        cpu_count = $VM.CPUCount
        memory = $VM.Memory
        host = if ($VM.VMHost) { $VM.VMHost.Name } else { $null }
        cloud = if ($VM.Cloud) { $VM.Cloud.Name } else { $null }
        vm_network = @()
        checkpoints = $VM.CheckpointCount
        creation_time = if ($VM.CreationTime) { $VM.CreationTime.ToString("yyyy-MM-ddTHH:mm:ss") } else { $null }
        description = $VM.Description
        owner = if ($VM.Owner) { $VM.Owner.UserName } else { $null }
        cost_center = $VM.CostCenter
        tag = $VM.Tag
        operating_system = if ($VM.OperatingSystem) { $VM.OperatingSystem.Name } else { $null }
        library_server = if ($VM.LibraryServer) { $VM.LibraryServer.Name } else { $null }
        enabled = $VM.Enabled
        is_highly_available = $VM.IsHighlyAvailable
        location = $VM.Location
        path = $VM.VMCPath
    }

    # Get network adapter information
    try {
        $adapters = Get-SCVirtualNetworkAdapter -VM $VM -ErrorAction SilentlyContinue
        if ($adapters) {
            foreach ($adapter in $adapters) {
                $adapterInfo = @{
                    name = $adapter.Name
                    mac_address = $adapter.MACAddress
                    vlan_enabled = $adapter.VLANEnabled
                    vlan_id = $adapter.VLANId
                    vm_network = if ($adapter.VMNetwork) { $adapter.VMNetwork.Name } else { $null }
                    vm_subnet = if ($adapter.VMSubnet) { $adapter.VMSubnet.Name } else { $null }
                    ipv4_addresses = @($adapter.IPv4Addresses)
                    ipv6_addresses = @($adapter.IPv6Addresses)
                }
                $vmInfo.vm_network += $adapterInfo
            }
        }
    } catch {
        # Network adapter info is optional, continue if it fails
    }

    return $vmInfo
}

try {
    # Connect to SCVMM server
    $vmmConnection = Connect-VMMServer -ServerName $vmm_server

    # Build filter parameters for Get-SCVirtualMachine
    $getVMParams = @{
        VMMServer = $vmmConnection
        ErrorAction = "Stop"
    }

    # Apply filters based on provided parameters
    if ($name) {
        $getVMParams.Name = $name
    }

    if ($id) {
        $getVMParams.ID = $id
    }

    # Get virtual machines
    $virtualMachines = Get-SCVirtualMachine @getVMParams

    if (-not $virtualMachines) {
        $virtualMachines = @()
    } elseif ($virtualMachines -isnot [array]) {
        $virtualMachines = @($virtualMachines)
    }

    # Apply additional filters that Get-SCVirtualMachine doesn't directly support
    if ($cloud) {
        $virtualMachines = $virtualMachines | Where-Object { $_.Cloud -and $_.Cloud.Name -eq $cloud }
    }

    if ($host_group) {
        $virtualMachines = $virtualMachines | Where-Object { $_.HostGroupPath -like "*$host_group*" }
    }

    if ($vm_host) {
        $virtualMachines = $virtualMachines | Where-Object { $_.VMHost -and $_.VMHost.Name -eq $vm_host }
    }

    if ($status) {
        $virtualMachines = $virtualMachines | Where-Object { $_.Status.ToString() -eq $status }
    }

    # Convert VMs to info objects
    foreach ($vm in $virtualMachines) {
        $vmInfo = Get-VMInfo -VM $vm
        $module.Result.vms += $vmInfo
    }

    $module.Result.changed = $false
    $module.ExitJson()

} catch {
    $module.FailJson("Failed to retrieve VM information: $($_.Exception.Message)", $_)
}
