#!powershell

# Copyright: (c) 2026, Generated by Jarvis Ansible Collection Swarm
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#AnsibleRequires -CSharpUtil Ansible.Basic

$spec = @{
    options = @{
        source_vm = @{ type = "str"; required = $true }
        clone_name = @{ type = "str"; required = $true }
        vmm_server = @{ type = "str"; required = $false }
        state = @{ type = "str"; default = "present"; choices = @("present", "absent") }

        # Placement options (mutually exclusive)
        vm_host = @{ type = "str"; required = $false }
        cloud = @{ type = "str"; required = $false }
        host_group = @{ type = "str"; required = $false }

        # Storage configuration
        path = @{ type = "str"; required = $false }

        # Network configuration
        vm_network = @{ type = "str"; required = $false }

        # Clone behavior
        description = @{ type = "str"; required = $false }
        start_vm = @{ type = "bool"; default = $false }

        # Hardware customization (override source VM)
        cpu_count = @{ type = "int"; required = $false }
        memory_mb = @{ type = "int"; required = $false }
    }
    mutually_exclusive = @(
        ,@("cloud", "vm_host")
    )
    supports_check_mode = $true
}

$module = [Ansible.Basic.AnsibleModule]::Create($args, $spec)

$source_vm = $module.Params.source_vm
$clone_name = $module.Params.clone_name
$vmm_server = $module.Params.vmm_server
$state = $module.Params.state
$vm_host = $module.Params.vm_host
$cloud = $module.Params.cloud
$host_group = $module.Params.host_group
$path = $module.Params.path
$vm_network = $module.Params.vm_network
$description = $module.Params.description
$start_vm = $module.Params.start_vm
$cpu_count = $module.Params.cpu_count
$memory_mb = $module.Params.memory_mb

# Initialize result
$module.Result.changed = $false
$module.Result.clone = @{}

# Import VirtualMachineManager module
try {
    Import-Module VirtualMachineManager -ErrorAction Stop
} catch {
    $module.FailJson("Failed to import VirtualMachineManager module. Ensure SCVMM PowerShell module is installed.", $_)
}

# Connect to SCVMM server
try {
    if ($vmm_server) {
        $vmmConnection = Get-SCVMMServer -ComputerName $vmm_server -ErrorAction Stop
    } else {
        $vmmConnection = Get-SCVMMServer -ErrorAction Stop
    }
} catch {
    $module.FailJson("Failed to connect to SCVMM server '$vmm_server'.", $_)
}

# Helper function to build VM properties for diff mode
Function Get-VmPropertiesDict {
    param($Vm)

    return @{
        name = $Vm.Name
        status = $Vm.Status
        cpu_count = $Vm.CPUCount
        memory_mb = $Vm.Memory
        description = $Vm.Description
        vm_host = $Vm.HostName
        cloud = if ($Vm.Cloud) { $Vm.Cloud.Name } else { $null }
        generation = $Vm.Generation
        vm_id = $Vm.ID
    }
}

# PATTERN: Check current state (GET)
# Check if source VM exists
try {
    $sourceVmObj = Get-SCVirtualMachine -VMMServer $vmmConnection -Name $source_vm -ErrorAction SilentlyContinue
    if ($null -eq $sourceVmObj) {
        $module.FailJson("Source VM '$source_vm' does not exist.")
    }
} catch {
    $module.FailJson("Failed to query source VM '$source_vm'.", $_)
}

# Check if clone already exists
try {
    $cloneVm = Get-SCVirtualMachine -VMMServer $vmmConnection -Name $clone_name -ErrorAction SilentlyContinue
} catch {
    $module.FailJson("Failed to query clone VM '$clone_name'.", $_)
}

# PATTERN: Decide action based on desired state
if ($state -eq "present") {
    if ($null -eq $cloneVm) {
        # Clone doesn't exist, create it
        $module.Diff.before = @{}

        if (-not $module.CheckMode) {
            try {
                # Build clone parameters
                $cloneParams = @{
                    VM = $sourceVmObj
                    Name = $clone_name
                    VMMServer = $vmmConnection
                }

                # Placement selection
                if ($cloud) {
                    $cloudObj = Get-SCCloud -VMMServer $vmmConnection -Name $cloud -ErrorAction Stop
                    $cloneParams.Cloud = $cloudObj
                } elseif ($vm_host) {
                    $vmHostObj = Get-SCVMHost -VMMServer $vmmConnection -ComputerName $vm_host -ErrorAction Stop
                    $cloneParams.VMHost = $vmHostObj
                } elseif ($host_group) {
                    $hostGroupObj = Get-SCVMHostGroup -VMMServer $vmmConnection -Name $host_group -ErrorAction Stop
                    $cloneParams.VMHostGroup = $hostGroupObj
                }

                # Storage path
                if ($path) {
                    $cloneParams.Path = $path
                }

                # Description
                if ($description) {
                    $cloneParams.Description = $description
                }

                # Start VM after cloning
                if ($start_vm) {
                    $cloneParams.StartVM = $true
                }

                # Run asynchronously for better performance
                $cloneParams.RunAsynchronously = $true

                # PATTERN: Apply change (CREATE/CLONE)
                $job = New-SCVirtualMachine @cloneParams

                # Wait for job completion
                do {
                    Start-Sleep -Seconds 2
                    $job = Get-SCJob -ID $job.ID
                } while ($job.Status -eq "Running")

                if ($job.Status -ne "Completed") {
                    $module.FailJson("Failed to clone VM from '$source_vm' to '$clone_name'. Job status: $($job.Status). Error: $($job.ErrorInfo)")
                }

                # Retrieve the cloned VM
                $cloneVm = Get-SCVirtualMachine -VMMServer $vmmConnection -Name $clone_name -ErrorAction Stop

                # Apply hardware customizations if specified
                if ($cpu_count -or $memory_mb -or $vm_network) {
                    $updateParams = @{
                        VM = $cloneVm
                    }

                    if ($cpu_count) {
                        $updateParams.CPUCount = $cpu_count
                    }

                    if ($memory_mb) {
                        $updateParams.MemoryMB = $memory_mb
                    }

                    # Apply hardware updates
                    if ($updateParams.Count -gt 1) {
                        $cloneVm = Set-SCVirtualMachine @updateParams -ErrorAction Stop
                    }

                    # Network configuration (requires separate operation)
                    if ($vm_network) {
                        $vmNet = Get-SCVMNetwork -VMMServer $vmmConnection -Name $vm_network -ErrorAction Stop
                        $vmNetAdapter = Get-SCVirtualNetworkAdapter -VM $cloneVm | Select-Object -First 1
                        if ($vmNetAdapter) {
                            Set-SCVirtualNetworkAdapter -VirtualNetworkAdapter $vmNetAdapter -VMNetwork $vmNet -ErrorAction Stop
                        }
                    }

                    # Refresh VM object after updates
                    $cloneVm = Get-SCVirtualMachine -VMMServer $vmmConnection -Name $clone_name -ErrorAction Stop
                }

            } catch {
                $module.FailJson("Failed to clone VM from '$source_vm' to '$clone_name'.", $_)
            }
        }

        $module.Result.changed = $true
        $module.Result.msg = "VM '$clone_name' cloned successfully from '$source_vm'"

        if (-not $module.CheckMode) {
            $module.Result.clone = Get-VmPropertiesDict -Vm $cloneVm
            $module.Diff.after = $module.Result.clone
        } else {
            $module.Diff.after = @{
                name = $clone_name
                status = "PoweredOff"
                source_vm = $source_vm
            }
        }

    } else {
        # Clone already exists
        $module.Diff.before = Get-VmPropertiesDict -Vm $cloneVm
        $module.Diff.after = $module.Diff.before

        $module.Result.changed = $false
        $module.Result.msg = "Clone VM '$clone_name' already exists"
        $module.Result.clone = Get-VmPropertiesDict -Vm $cloneVm
    }

} else {
    # state == "absent"
    if ($null -ne $cloneVm) {
        # Clone exists, remove it
        $module.Diff.before = Get-VmPropertiesDict -Vm $cloneVm
        $module.Diff.after = @{}

        if (-not $module.CheckMode) {
            try {
                # PATTERN: Apply change (DELETE)
                Remove-SCVirtualMachine -VM $cloneVm -Force -ErrorAction Stop
            } catch {
                $module.FailJson("Failed to remove clone VM '$clone_name'.", $_)
            }
        }

        $module.Result.changed = $true
        $module.Result.msg = "Clone VM '$clone_name' removed successfully"

    } else {
        $module.Result.changed = $false
        $module.Result.msg = "Clone VM '$clone_name' already absent"
        $module.Diff.before = @{}
        $module.Diff.after = @{}
    }
}

$module.ExitJson()
