#!powershell

# Copyright: (c) 2026, Generated by Jarvis Ansible Collection Swarm
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#AnsibleRequires -CSharpUtil Ansible.Basic

$spec = @{
    options = @{
        name = @{ type = "str"; required = $true }
        vmm_server = @{ type = "str"; required = $false }
        state = @{ type = "str"; default = "present"; choices = @("present", "absent") }

        # Source selection (mutually exclusive)
        template = @{ type = "str"; required = $false }
        vm_host = @{ type = "str"; required = $false }
        cloud = @{ type = "str"; required = $false }
        host_group = @{ type = "str"; required = $false }

        # Hardware configuration
        cpu_count = @{ type = "int"; required = $false }
        memory_mb = @{ type = "int"; required = $false }
        dynamic_memory_enabled = @{ type = "bool"; required = $false }
        dynamic_memory_min_mb = @{ type = "int"; required = $false }
        dynamic_memory_max_mb = @{ type = "int"; required = $false }
        hardware_profile = @{ type = "str"; required = $false }
        generation = @{ type = "int"; choices = @(1, 2); required = $false }

        # Guest OS customization
        computer_name = @{ type = "str"; required = $false }
        guest_os_profile = @{ type = "str"; required = $false }
        full_name = @{ type = "str"; required = $false }
        organization_name = @{ type = "str"; required = $false }
        product_key = @{ type = "str"; required = $false; no_log = $true }
        time_zone = @{ type = "int"; required = $false }
        domain = @{ type = "str"; required = $false }
        workgroup = @{ type = "str"; required = $false }
        local_admin_password = @{ type = "str"; required = $false; no_log = $true }

        # Network configuration
        vm_network = @{ type = "str"; required = $false }

        # VM behavior
        description = @{ type = "str"; required = $false }
        start_action = @{ type = "str"; choices = @("NeverAutoTurnOnVM", "AlwaysAutoTurnOnVM", "TurnOnVMIfRunningWhenVSStopped"); required = $false }
        stop_action = @{ type = "str"; choices = @("SaveVM", "TurnOffVM", "ShutdownGuestOS"); required = $false }
        delay_start_seconds = @{ type = "int"; required = $false }

        # Advanced features
        highly_available = @{ type = "bool"; required = $false }
        enable_nested_virtualization = @{ type = "bool"; required = $false }
        secure_boot_enabled = @{ type = "bool"; required = $false }
        checkpoint_type = @{ type = "str"; choices = @("Disabled", "Production", "Standard"); required = $false }

        # Post-creation behavior
        start_vm = @{ type = "bool"; default = $false }

        # Storage
        path = @{ type = "str"; required = $false }
    }
    required_if = @(
        ,@("state", "present", @("template", "cloud"), $true)
    )
    mutually_exclusive = @(
        ,@("cloud", "vm_host")
        ,@("domain", "workgroup")
    )
    supports_check_mode = $true
}

$module = [Ansible.Basic.AnsibleModule]::Create($args, $spec)

$name = $module.Params.name
$vmm_server = $module.Params.vmm_server
$state = $module.Params.state
$template = $module.Params.template
$vm_host = $module.Params.vm_host
$cloud = $module.Params.cloud
$host_group = $module.Params.host_group
$cpu_count = $module.Params.cpu_count
$memory_mb = $module.Params.memory_mb
$dynamic_memory_enabled = $module.Params.dynamic_memory_enabled
$dynamic_memory_min_mb = $module.Params.dynamic_memory_min_mb
$dynamic_memory_max_mb = $module.Params.dynamic_memory_max_mb
$hardware_profile = $module.Params.hardware_profile
$generation = $module.Params.generation
$computer_name = $module.Params.computer_name
$guest_os_profile = $module.Params.guest_os_profile
$full_name = $module.Params.full_name
$organization_name = $module.Params.organization_name
$product_key = $module.Params.product_key
$time_zone = $module.Params.time_zone
$domain = $module.Params.domain
$workgroup = $module.Params.workgroup
$local_admin_password = $module.Params.local_admin_password
$vm_network = $module.Params.vm_network
$description = $module.Params.description
$start_action = $module.Params.start_action
$stop_action = $module.Params.stop_action
$delay_start_seconds = $module.Params.delay_start_seconds
$highly_available = $module.Params.highly_available
$enable_nested_virtualization = $module.Params.enable_nested_virtualization
$secure_boot_enabled = $module.Params.secure_boot_enabled
$checkpoint_type = $module.Params.checkpoint_type
$start_vm = $module.Params.start_vm
$path = $module.Params.path

# Initialize result
$module.Result.changed = $false
$module.Result.vm = @{}

# Import VirtualMachineManager module
try {
    Import-Module VirtualMachineManager -ErrorAction Stop
} catch {
    $module.FailJson("Failed to import VirtualMachineManager module. Ensure SCVMM PowerShell module is installed.", $_)
}

# Connect to SCVMM server
try {
    if ($vmm_server) {
        $vmmConnection = Get-SCVMMServer -ComputerName $vmm_server -ErrorAction Stop
    } else {
        $vmmConnection = Get-SCVMMServer -ErrorAction Stop
    }
} catch {
    $module.FailJson("Failed to connect to SCVMM server '$vmm_server'.", $_)
}

# Helper function to compare VM properties
Function Compare-VmProperties {
    param(
        $CurrentVm,
        $DesiredProperties
    )

    $differences = @()

    if ($null -ne $DesiredProperties.cpu_count -and $CurrentVm.CPUCount -ne $DesiredProperties.cpu_count) {
        $differences += @{property = "CPUCount"; current = $CurrentVm.CPUCount; desired = $DesiredProperties.cpu_count}
    }

    if ($null -ne $DesiredProperties.memory_mb -and $CurrentVm.Memory -ne $DesiredProperties.memory_mb) {
        $differences += @{property = "Memory"; current = $CurrentVm.Memory; desired = $DesiredProperties.memory_mb}
    }

    if ($null -ne $DesiredProperties.dynamic_memory_enabled -and $CurrentVm.DynamicMemoryEnabled -ne $DesiredProperties.dynamic_memory_enabled) {
        $differences += @{property = "DynamicMemoryEnabled"; current = $CurrentVm.DynamicMemoryEnabled; desired = $DesiredProperties.dynamic_memory_enabled}
    }

    if ($null -ne $DesiredProperties.dynamic_memory_min_mb -and $CurrentVm.DynamicMemoryEnabled -and $CurrentVm.DynamicMemoryMinimumMB -ne $DesiredProperties.dynamic_memory_min_mb) {
        $differences += @{property = "DynamicMemoryMinimumMB"; current = $CurrentVm.DynamicMemoryMinimumMB; desired = $DesiredProperties.dynamic_memory_min_mb}
    }

    if ($null -ne $DesiredProperties.dynamic_memory_max_mb -and $CurrentVm.DynamicMemoryEnabled -and $CurrentVm.DynamicMemoryMaximumMB -ne $DesiredProperties.dynamic_memory_max_mb) {
        $differences += @{property = "DynamicMemoryMaximumMB"; current = $CurrentVm.DynamicMemoryMaximumMB; desired = $DesiredProperties.dynamic_memory_max_mb}
    }

    if ($null -ne $DesiredProperties.description -and $CurrentVm.Description -ne $DesiredProperties.description) {
        $differences += @{property = "Description"; current = $CurrentVm.Description; desired = $DesiredProperties.description}
    }

    if ($null -ne $DesiredProperties.start_action -and $CurrentVm.StartAction -ne $DesiredProperties.start_action) {
        $differences += @{property = "StartAction"; current = $CurrentVm.StartAction; desired = $DesiredProperties.start_action}
    }

    if ($null -ne $DesiredProperties.stop_action -and $CurrentVm.StopAction -ne $DesiredProperties.stop_action) {
        $differences += @{property = "StopAction"; current = $CurrentVm.StopAction; desired = $DesiredProperties.stop_action}
    }

    if ($null -ne $DesiredProperties.delay_start_seconds -and $CurrentVm.DelayStartSeconds -ne $DesiredProperties.delay_start_seconds) {
        $differences += @{property = "DelayStartSeconds"; current = $CurrentVm.DelayStartSeconds; desired = $DesiredProperties.delay_start_seconds}
    }

    if ($null -ne $DesiredProperties.checkpoint_type -and $CurrentVm.CheckpointType -ne $DesiredProperties.checkpoint_type) {
        $differences += @{property = "CheckpointType"; current = $CurrentVm.CheckpointType; desired = $DesiredProperties.checkpoint_type}
    }

    return $differences
}

# Helper function to build VM properties for diff mode
Function Get-VmPropertiesDict {
    param($Vm)

    return @{
        name = $Vm.Name
        status = $Vm.Status
        cpu_count = $Vm.CPUCount
        memory_mb = $Vm.Memory
        dynamic_memory_enabled = $Vm.DynamicMemoryEnabled
        dynamic_memory_min_mb = $Vm.DynamicMemoryMinimumMB
        dynamic_memory_max_mb = $Vm.DynamicMemoryMaximumMB
        description = $Vm.Description
        start_action = $Vm.StartAction
        stop_action = $Vm.StopAction
        delay_start_seconds = $Vm.DelayStartSeconds
        checkpoint_type = $Vm.CheckpointType
        vm_host = $Vm.HostName
        cloud = if ($Vm.Cloud) { $Vm.Cloud.Name } else { $null }
        generation = $Vm.Generation
    }
}

# PATTERN: Check current state (GET)
try {
    $currentVm = Get-SCVirtualMachine -VMMServer $vmmConnection -Name $name -ErrorAction SilentlyContinue
} catch {
    $module.FailJson("Failed to query VM '$name'.", $_)
}

# PATTERN: Decide action based on desired state
if ($state -eq "present") {
    if ($null -eq $currentVm) {
        # VM doesn't exist, create it
        $module.Diff.before = @{}

        # Validate required parameters for creation
        if (-not $template -and -not $cloud) {
            $module.FailJson("Either 'template' or 'cloud' is required when creating a new VM.")
        }

        if (-not $module.CheckMode) {
            try {
                # Build creation parameters
                $createParams = @{
                    Name = $name
                    VMMServer = $vmmConnection
                }

                # Source selection
                if ($template) {
                    $vmTemplate = Get-SCVMTemplate -VMMServer $vmmConnection -Name $template -ErrorAction Stop
                    $createParams.VMTemplate = $vmTemplate
                }

                if ($cloud) {
                    $cloudObj = Get-SCCloud -VMMServer $vmmConnection -Name $cloud -ErrorAction Stop
                    $createParams.Cloud = $cloudObj
                } elseif ($vm_host) {
                    $vmHostObj = Get-SCVMHost -VMMServer $vmmConnection -ComputerName $vm_host -ErrorAction Stop
                    $createParams.VMHost = $vmHostObj
                } elseif ($host_group) {
                    $hostGroupObj = Get-SCVMHostGroup -VMMServer $vmmConnection -Name $host_group -ErrorAction Stop
                    $createParams.VMHostGroup = $hostGroupObj
                }

                # Storage path
                if ($path) {
                    $createParams.Path = $path
                }

                # Hardware configuration
                if ($cpu_count) {
                    $createParams.CPUCount = $cpu_count
                }

                if ($memory_mb) {
                    $createParams.MemoryMB = $memory_mb
                }

                if ($null -ne $dynamic_memory_enabled) {
                    $createParams.DynamicMemoryEnabled = $dynamic_memory_enabled
                }

                if ($dynamic_memory_min_mb) {
                    $createParams.DynamicMemoryMinimumMB = $dynamic_memory_min_mb
                }

                if ($dynamic_memory_max_mb) {
                    $createParams.DynamicMemoryMaximumMB = $dynamic_memory_max_mb
                }

                if ($hardware_profile) {
                    $hwProfile = Get-SCHardwareProfile -VMMServer $vmmConnection -Name $hardware_profile -ErrorAction Stop
                    $createParams.HardwareProfile = $hwProfile
                }

                if ($generation) {
                    $createParams.Generation = $generation
                }

                # Guest OS customization
                if ($computer_name) {
                    $createParams.ComputerName = $computer_name
                }

                if ($guest_os_profile) {
                    $guestProfile = Get-SCGuestOSProfile -VMMServer $vmmConnection -Name $guest_os_profile -ErrorAction Stop
                    $createParams.GuestOSProfile = $guestProfile
                }

                if ($full_name) {
                    $createParams.FullName = $full_name
                }

                if ($organization_name) {
                    $createParams.OrgName = $organization_name
                }

                if ($product_key) {
                    $createParams.ProductKey = $product_key
                }

                if ($time_zone) {
                    $createParams.TimeZone = $time_zone
                }

                if ($domain) {
                    $createParams.Domain = $domain
                }

                if ($workgroup) {
                    $createParams.Workgroup = $workgroup
                }

                if ($local_admin_password) {
                    $securePassword = ConvertTo-SecureString $local_admin_password -AsPlainText -Force
                    $createParams.LocalAdministratorPassword = $securePassword
                }

                # Network
                if ($vm_network) {
                    $vmNet = Get-SCVMNetwork -VMMServer $vmmConnection -Name $vm_network -ErrorAction Stop
                    $createParams.VMNetwork = $vmNet
                }

                # VM behavior
                if ($description) {
                    $createParams.Description = $description
                }

                if ($start_action) {
                    $createParams.StartAction = $start_action
                }

                if ($stop_action) {
                    $createParams.StopAction = $stop_action
                }

                if ($delay_start_seconds) {
                    $createParams.DelayStartSeconds = $delay_start_seconds
                }

                # Advanced features
                if ($null -ne $highly_available) {
                    $createParams.HighlyAvailable = $highly_available
                }

                if ($null -ne $enable_nested_virtualization) {
                    $createParams.EnableNestedVirtualization = $enable_nested_virtualization
                }

                if ($null -ne $secure_boot_enabled) {
                    $createParams.SecureBootEnabled = $secure_boot_enabled
                }

                if ($checkpoint_type) {
                    $createParams.CheckpointType = $checkpoint_type
                }

                # Start VM after creation
                if ($start_vm) {
                    $createParams.StartVM = $true
                }

                # Run asynchronously for better performance
                $createParams.RunAsynchronously = $true

                # PATTERN: Apply change (CREATE)
                $job = New-SCVirtualMachine @createParams

                # Wait for job completion
                do {
                    Start-Sleep -Seconds 2
                    $job = Get-SCJob -ID $job.ID
                } while ($job.Status -eq "Running")

                if ($job.Status -ne "Completed") {
                    $module.FailJson("Failed to create VM '$name'. Job status: $($job.Status). Error: $($job.ErrorInfo)")
                }

                # Retrieve the created VM
                $currentVm = Get-SCVirtualMachine -VMMServer $vmmConnection -Name $name -ErrorAction Stop

            } catch {
                $module.FailJson("Failed to create VM '$name'.", $_)
            }
        }

        $module.Result.changed = $true
        $module.Result.msg = "VM '$name' created successfully"

        if (-not $module.CheckMode) {
            $module.Result.vm = Get-VmPropertiesDict -Vm $currentVm
            $module.Diff.after = $module.Result.vm
        } else {
            $module.Diff.after = @{
                name = $name
                status = "PoweredOff"
            }
        }

    } else {
        # VM exists, check if update needed
        $module.Diff.before = Get-VmPropertiesDict -Vm $currentVm

        # Build desired properties for comparison
        $desiredProps = @{
            cpu_count = $cpu_count
            memory_mb = $memory_mb
            dynamic_memory_enabled = $dynamic_memory_enabled
            dynamic_memory_min_mb = $dynamic_memory_min_mb
            dynamic_memory_max_mb = $dynamic_memory_max_mb
            description = $description
            start_action = $start_action
            stop_action = $stop_action
            delay_start_seconds = $delay_start_seconds
            checkpoint_type = $checkpoint_type
        }

        # PATTERN: Compare current vs desired
        $differences = Compare-VmProperties -CurrentVm $currentVm -DesiredProperties $desiredProps

        if ($differences.Count -gt 0) {
            if (-not $module.CheckMode) {
                try {
                    # Build update parameters
                    $updateParams = @{
                        VM = $currentVm
                    }

                    foreach ($diff in $differences) {
                        switch ($diff.property) {
                            "CPUCount" { $updateParams.CPUCount = $diff.desired }
                            "Memory" { $updateParams.MemoryMB = $diff.desired }
                            "DynamicMemoryEnabled" { $updateParams.DynamicMemoryEnabled = $diff.desired }
                            "DynamicMemoryMinimumMB" { $updateParams.DynamicMemoryMinimumMB = $diff.desired }
                            "DynamicMemoryMaximumMB" { $updateParams.DynamicMemoryMaximumMB = $diff.desired }
                            "Description" { $updateParams.Description = $diff.desired }
                            "StartAction" { $updateParams.StartAction = $diff.desired }
                            "StopAction" { $updateParams.StopAction = $diff.desired }
                            "DelayStartSeconds" { $updateParams.DelayStartSeconds = $diff.desired }
                            "CheckpointType" { $updateParams.CheckpointType = $diff.desired }
                        }
                    }

                    # PATTERN: Apply change (UPDATE)
                    $updatedVm = Set-SCVirtualMachine @updateParams -ErrorAction Stop
                    $currentVm = $updatedVm

                } catch {
                    $module.FailJson("Failed to update VM '$name'.", $_)
                }
            }

            $module.Result.changed = $true
            $module.Result.msg = "VM '$name' updated successfully"
            $module.Result.differences = $differences

        } else {
            $module.Result.changed = $false
            $module.Result.msg = "VM '$name' already in desired state"
        }

        if (-not $module.CheckMode) {
            $module.Result.vm = Get-VmPropertiesDict -Vm $currentVm
            $module.Diff.after = $module.Result.vm
        } else {
            $module.Diff.after = $module.Diff.before
            if ($differences.Count -gt 0) {
                foreach ($diff in $differences) {
                    $propName = $diff.property.ToLower() -replace "mb$", "_mb"
                    $module.Diff.after[$propName] = $diff.desired
                }
            }
        }
    }

} else {
    # state == "absent"
    if ($null -ne $currentVm) {
        # VM exists, remove it
        $module.Diff.before = Get-VmPropertiesDict -Vm $currentVm
        $module.Diff.after = @{}

        if (-not $module.CheckMode) {
            try {
                # PATTERN: Apply change (DELETE)
                Remove-SCVirtualMachine -VM $currentVm -Force -ErrorAction Stop
            } catch {
                $module.FailJson("Failed to remove VM '$name'.", $_)
            }
        }

        $module.Result.changed = $true
        $module.Result.msg = "VM '$name' removed successfully"

    } else {
        $module.Result.changed = $false
        $module.Result.msg = "VM '$name' already absent"
        $module.Diff.before = @{}
        $module.Diff.after = @{}
    }
}

$module.ExitJson()
