#!powershell

# Copyright: (c) 2026, Generated by Jarvis Universal Ansible Collection Swarm
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#AnsibleRequires -CSharpUtil Ansible.Basic

$spec = @{
    options = @{
        vm_name = @{
            type = "str"
            required = $true
        }
        vmm_server = @{
            type = "str"
            required = $true
        }
        adapter_id = @{
            type = "int"
            required = $false
        }
        scsi_controller_type = @{
            type = "str"
            required = $false
            choices = @("DefaultTypeNoType", "LsiLogic", "LsiLogicSAS", "BusLogic", "ParaVirtualSCSI")
            default = "DefaultTypeNoType"
        }
        state = @{
            type = "str"
            required = $true
            choices = @("present", "absent")
        }
    }
    supports_check_mode = $true
}

$module = [Ansible.Basic.AnsibleModule]::Create($args, $spec)

$vm_name = $module.Params.vm_name
$vmm_server = $module.Params.vmm_server
$adapter_id = $module.Params.adapter_id
$scsi_controller_type = $module.Params.scsi_controller_type
$state = $module.Params.state

$module.Result.changed = $false
$module.Result.vm_name = $vm_name
$module.Result.adapter = @{}

# Import VirtualMachineManager module
try {
    Import-Module VirtualMachineManager -ErrorAction Stop
} catch {
    $module.FailJson("Failed to import VirtualMachineManager module. Ensure SCVMM PowerShell module is installed.", $_)
}

# Connect to SCVMM server
try {
    $vmmConnection = Get-SCVMMServer -ComputerName $vmm_server -ErrorAction Stop
} catch {
    $module.FailJson("Failed to connect to SCVMM server '$vmm_server'.", $_)
}

# Get the VM
try {
    $vm = Get-SCVirtualMachine -VMMServer $vmmConnection -Name $vm_name -ErrorAction Stop
} catch {
    $module.FailJson("Failed to find VM '$vm_name'.", $_)
}

# Helper function to get adapter properties
Function Get-AdapterPropertiesDict {
    param($Adapter)

    if ($null -eq $Adapter) {
        return @{}
    }

    return @{
        adapter_id = $Adapter.ID.ToString()
        scsi_controller_type = $Adapter.SCSIControllerType
        scsi_bus = $Adapter.Bus
        scsi_lun = $Adapter.Lun
        name = $Adapter.Name
    }
}

# PATTERN: Check current state (GET)
try {
    $currentAdapters = Get-SCVirtualScsiAdapter -VM $vm -ErrorAction SilentlyContinue

    if ($null -eq $currentAdapters) {
        $currentAdapters = @()
    } elseif ($currentAdapters -isnot [System.Array]) {
        $currentAdapters = @($currentAdapters)
    }
} catch {
    $module.FailJson("Failed to query SCSI adapters for VM '$vm_name'.", $_)
}

# Find specific adapter by ID if provided
$targetAdapter = $null
if ($null -ne $adapter_id) {
    foreach ($adapter in $currentAdapters) {
        if ($adapter.Bus -eq $adapter_id) {
            $targetAdapter = $adapter
            break
        }
    }
}

# PATTERN: Decide action based on desired state
if ($state -eq "present") {

    # If adapter_id is specified, check if it exists
    if ($null -ne $adapter_id) {
        if ($null -eq $targetAdapter) {
            # Adapter with specified ID doesn't exist, create it
            $module.Diff.before = @{}

            if (-not $module.CheckMode) {
                try {
                    # Build creation parameters
                    $createParams = @{
                        VM = $vm
                        Bus = $adapter_id
                    }

                    if ($scsi_controller_type -ne "DefaultTypeNoType") {
                        $createParams.SCSIControllerType = $scsi_controller_type
                    }

                    # PATTERN: Apply change (CREATE)
                    $targetAdapter = New-SCVirtualScsiAdapter @createParams -ErrorAction Stop

                } catch {
                    $module.FailJson("Failed to create SCSI adapter with ID '$adapter_id' for VM '$vm_name'.", $_)
                }
            }

            $module.Result.changed = $true
            $module.Result.msg = "SCSI adapter with ID '$adapter_id' created successfully"

            if (-not $module.CheckMode) {
                $module.Result.adapter = Get-AdapterPropertiesDict -Adapter $targetAdapter
                $module.Diff.after = $module.Result.adapter
            } else {
                $module.Diff.after = @{
                    adapter_id = "N/A (check mode)"
                    scsi_controller_type = $scsi_controller_type
                    scsi_bus = $adapter_id
                }
            }

        } else {
            # Adapter exists, check if update needed
            $module.Diff.before = Get-AdapterPropertiesDict -Adapter $targetAdapter

            # Compare controller type if provided
            $needsUpdate = $false
            if ($scsi_controller_type -ne "DefaultTypeNoType" -and $targetAdapter.SCSIControllerType -ne $scsi_controller_type) {
                $needsUpdate = $true
            }

            if ($needsUpdate) {
                # SCVMM does not support modifying SCSI adapter controller type after creation
                $module.Warn("SCVMM does not support modifying SCSI adapter controller type after creation. Adapter exists but controller type cannot be changed.")
                $module.Result.changed = $false
                $module.Result.msg = "SCSI adapter '$adapter_id' exists but cannot be updated (SCVMM limitation)"
            } else {
                $module.Result.changed = $false
                $module.Result.msg = "SCSI adapter '$adapter_id' already exists"
            }

            if (-not $module.CheckMode) {
                $module.Result.adapter = Get-AdapterPropertiesDict -Adapter $targetAdapter
                $module.Diff.after = $module.Result.adapter
            } else {
                $module.Diff.after = $module.Diff.before
            }
        }
    } else {
        # No adapter_id specified, create a new adapter with next available ID
        if ($currentAdapters.Count -eq 0) {
            # No adapters exist, create the first one (Bus 0)
            $nextBusId = 0
        } else {
            # Find the next available Bus ID
            $usedBusIds = $currentAdapters | ForEach-Object { $_.Bus } | Sort-Object
            $nextBusId = 0
            foreach ($busId in $usedBusIds) {
                if ($busId -eq $nextBusId) {
                    $nextBusId++
                } else {
                    break
                }
            }
        }

        $module.Diff.before = @{}

        if (-not $module.CheckMode) {
            try {
                # Build creation parameters
                $createParams = @{
                    VM = $vm
                    Bus = $nextBusId
                }

                if ($scsi_controller_type -ne "DefaultTypeNoType") {
                    $createParams.SCSIControllerType = $scsi_controller_type
                }

                # PATTERN: Apply change (CREATE)
                $targetAdapter = New-SCVirtualScsiAdapter @createParams -ErrorAction Stop

            } catch {
                $module.FailJson("Failed to create SCSI adapter for VM '$vm_name'.", $_)
            }
        }

        $module.Result.changed = $true
        $module.Result.msg = "SCSI adapter created successfully with ID '$nextBusId'"

        if (-not $module.CheckMode) {
            $module.Result.adapter = Get-AdapterPropertiesDict -Adapter $targetAdapter
            $module.Diff.after = $module.Result.adapter
        } else {
            $module.Diff.after = @{
                adapter_id = "N/A (check mode)"
                scsi_controller_type = $scsi_controller_type
                scsi_bus = $nextBusId
            }
        }
    }

} elseif ($state -eq "absent") {
    # state == "absent"

    if ($null -ne $adapter_id) {
        # Remove specific adapter by ID
        if ($null -ne $targetAdapter) {
            # Adapter exists, remove it
            $module.Diff.before = Get-AdapterPropertiesDict -Adapter $targetAdapter
            $module.Diff.after = @{}

            if (-not $module.CheckMode) {
                try {
                    # PATTERN: Apply change (DELETE)
                    Remove-SCVirtualScsiAdapter -VirtualScsiAdapter $targetAdapter -ErrorAction Stop

                } catch {
                    $module.FailJson("Failed to remove SCSI adapter '$adapter_id' for VM '$vm_name'.", $_)
                }
            }

            $module.Result.changed = $true
            $module.Result.msg = "SCSI adapter '$adapter_id' removed successfully"

        } else {
            $module.Result.changed = $false
            $module.Result.msg = "SCSI adapter '$adapter_id' already absent"
            $module.Diff.before = @{}
            $module.Diff.after = @{}
        }
    } else {
        # Remove all adapters
        if ($currentAdapters.Count -gt 0) {
            $module.Diff.before = @{
                adapter_count = $currentAdapters.Count
                adapters = $currentAdapters | ForEach-Object { Get-AdapterPropertiesDict -Adapter $_ }
            }
            $module.Diff.after = @{
                adapter_count = 0
                adapters = @()
            }

            if (-not $module.CheckMode) {
                try {
                    foreach ($adapter in $currentAdapters) {
                        # PATTERN: Apply change (DELETE)
                        Remove-SCVirtualScsiAdapter -VirtualScsiAdapter $adapter -ErrorAction Stop
                    }

                } catch {
                    $module.FailJson("Failed to remove SCSI adapters for VM '$vm_name'.", $_)
                }
            }

            $module.Result.changed = $true
            $module.Result.msg = "All SCSI adapters ($($currentAdapters.Count)) removed successfully"

        } else {
            $module.Result.changed = $false
            $module.Result.msg = "No SCSI adapters to remove"
            $module.Diff.before = @{}
            $module.Diff.after = @{}
        }
    }
}

$module.ExitJson()
